version: "3.9"
services:
  api:
    container_name: dev1
    image: registry.gitlab.com/lateefat1/dev1:latest
    networks:
      - backend
    volumes:
    - type: volume
      source: dev1-vol
      target: /app
  nodered:
    container_name: nodered
    image: registry.gitlab.com/lateefat1/nodered:latest
    networks:
      - backend
    ports:
      - "1880:1880"
    volumes:
      - type: volume
        source: nodered-vol
        target: /data
    environment:
      - INFLUXDB_TOKEN=<token>
  influxdb:
    container_name: influxdb
    image: registry.gitlab.com/lateefat1/influxdb:latest
    networks:
      - backend
    volumes:
      - type: volume
        source: influxdb-vol
        target: /var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=<username>
      - DOCKER_INFLUXDB_INIT_PASSWORD=<password>
      - DOCKER_INFLUXDB_INIT_ORG=<org name>
      - DOCKER_INFLUXDB_INIT_BUCKET=<bucketname>
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=<token>
  grafana:
    container_name: grafana
    image: registry.gitlab.com/lateefat1/grafana:latest
    networks:
      - frontend
      - backend
      - db
    ports:
      - "3000:3000"
    # network_mode: service:wireguard
    volumes:
      - type: volume
        source: grafana-vol
        target: /var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=<username>
      - GF_SECURITY_ADMIN_PASSWORD=<password>
      - INFLUXDB_TOKEN=<token>
      - POSTGRES_USER=<username>
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=<DB>
  postgres:
    container_name: postgres
    image: registry.gitlab.com/lateefat1/postgres:latest
    networks:
      - db
    volumes:
      - type: volume
        source: postgres-vol
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=<username>
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=<DB>
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    networks:
      - backend
      - db
    environment:
      - PGRST_DB_URI=<postgres URL>
      - PGRST_DB_ANON_ROLE=<username>
      - PGRST_DB_SCHEMA=public
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PEERS=3
    volumes:
      - /home/ubuntu/environment/infrastructure/wireguard/config:/config:rw
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
volumes:
  dev1-vol: {}
  nodered-vol: {}
  influxdb-vol: {}
  grafana-vol: {}
  postgres-vol: {}
networks:
    frontend: {}
    backend: {}
    db: {}
